[build]
builder = "DOCKERFILE"

[deploy]
# NOTE: Currently migrate on start
# preDeployCommand = "bun run db:migrate"
healthcheckPath = "/health"
restartPolicyType = "ALWAYS"
drainingSeconds = 5
runtime = "V2"
numReplicas = 1

[deploy.limitOverride.containers]
cpu = 1
memoryBytes = 2000000000
